### ISSUE TITLE
Suggestion: Debian/Ubuntu compatibility

### ISSUE THREAD

**Issue by totordev** [Ryhon0/xp#3]
Hi, could you make xp compatible with Debian (if it's possible)? I really love this program, and I wanted to try it. But I am on Debian.

**Comment by Ryhon0** [comment]
Will try to make it work on Debian soon. As far as I know the only thing stopping it would be modest, which will be removed in the next major update

**Comment by totordev** [comment]
To give more information, when I try to install the dependencies, apt says that a lot of them are not avaliable. I haven't tried with Linuxbrew yet.
Edit: Using Linuxbrew, only liblphobos and modest are not here. liblphobos too is not avaliable.

**Comment by Ryhon0** [comment]
It looks like LDC statically links phobos now so lphobos is no longer required.
These should be the required packages for Debian 11:
```
ffmpeg
libtagc0
libsdl2-mixer-2.0-0
sqlite3
youtube-dl
```
Alternatively instead of `youtube-dl` you can use `yt-dlp` from the Multimedia Main repository
For building, these packages are required:
```
gcc
libsqlite3-dev
libdbus-1-dev
libtag1-dev
libtagc0-dev
```
Debian 11 seems to have an old version of `dub` that does not support adding repositories directly from git repos so you have to download LDC, which is packaged with `dub` from the releases [here](https://github.com/ldc-developers/ldc/releases/tag/v1.32.2) or use any other D compiler. GCC can also be replaced with any C compiler

**Comment by totordev** [comment]
Ok, thank you so much for your help. I'll see if it works.

**Comment by Ryhon0** [comment]
libmodest is the only blocker right now

**Comment by Ryhon0** [comment]
It might work now. I've tried building it in distrobox but it crashed, might be because it doesn't have dbus running.
Also, you need to download the `git` and `python` packages to build the program

**Comment by Ryhon0** [comment]
Seems to be getting stuck at Mix_Init, not sure why

**Comment by Ryhon0** [comment]
Actualy, nevermind. Started to working after I installed the dev package for SDL Mixer, probably an issue with Debian 12

**Comment by totordev** [comment]
Switched to pacman package manager. Might work

**Comment by totordev** [comment]
When I try to build, it tells me that the file "libtermbox.a" doesn't exist. Do I have to install it with pacman?

**Comment by Ryhon0** [comment]
It's compiled with the program, it failed to build, can you post the logs?

**Comment by totordev** [comment]
Nevermind, I ran `sudo pacman -S libtermbox-dev libtermbox1` and it worked
